[ERROR] 2017-07-11 23:14:45,017-log.py:92 Traceback (most recent call last):
  File "login.py", line 47, in input_username_passwd
    click_button = self.testdriver.find_element_by_xpath('//*[@id="userForLogin"]/div[4]/button')
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 313, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 791, in find_element
    'value': value})['value']
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: Unable to locate element: //*[@id="userForLogin"]/div[4]/button

Traceback (most recent call last):
  File "login.py", line 47, in input_username_passwd
    click_button = self.testdriver.find_element_by_xpath('//*[@id="userForLogin"]/div[4]/button')
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 313, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 791, in find_element
    'value': value})['value']
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: Unable to locate element: //*[@id="userForLogin"]/div[4]/button

[ERROR] 2017-07-11 23:34:27,602-torndb.py:236 Error connecting to MySQL on localhost
[ERROR] 2017-07-11 23:41:59,845-log.py:92 Traceback (most recent call last):
  File "login.py", line 44, in input_username_passwd
    userName = self.testdriver.find_element_by_id("userName")
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 289, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 791, in find_element
    'value': value})['value']
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: Unable to locate element: [id="userName"]

Traceback (most recent call last):
  File "login.py", line 44, in input_username_passwd
    userName = self.testdriver.find_element_by_id("userName")
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 289, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 791, in find_element
    'value': value})['value']
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: Unable to locate element: [id="userName"]

[ERROR] 2017-07-11 23:45:01,700-log.py:92 Traceback (most recent call last):
  File "login.py", line 44, in input_username_passwd
    userName = self.testdriver.find_element_by_id("userName")
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 289, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 791, in find_element
    'value': value})['value']
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: Unable to locate element: [id="userName"]

Traceback (most recent call last):
  File "login.py", line 44, in input_username_passwd
    userName = self.testdriver.find_element_by_id("userName")
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 289, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 791, in find_element
    'value': value})['value']
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: Unable to locate element: [id="userName"]

[ERROR] 2017-07-11 23:46:18,293-log.py:92 Traceback (most recent call last):
  File "login.py", line 44, in input_username_passwd
    userName = self.testdriver.find_element_by_id("userName")
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 289, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 791, in find_element
    'value': value})['value']
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: Unable to locate element: [id="userName"]

Traceback (most recent call last):
  File "login.py", line 44, in input_username_passwd
    userName = self.testdriver.find_element_by_id("userName")
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 289, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 791, in find_element
    'value': value})['value']
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: Unable to locate element: [id="userName"]

[ERROR] 2017-07-11 23:57:13,378-log.py:92 Traceback (most recent call last):
  File "login.py", line 63, in get_failed_page_message
    err_msg = self.testdriver.find_element_by_xpath('//*[@id="userForLogin"]/div[1]')
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 313, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 791, in find_element
    'value': value})['value']
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: Unable to locate element: //*[@id="userForLogin"]/div[1]

Traceback (most recent call last):
  File "login.py", line 63, in get_failed_page_message
    err_msg = self.testdriver.find_element_by_xpath('//*[@id="userForLogin"]/div[1]')
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 313, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 791, in find_element
    'value': value})['value']
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: Unable to locate element: //*[@id="userForLogin"]/div[1]

[ERROR] 2017-07-11 23:57:13,670-log.py:92 Traceback (most recent call last):
  File "login.py", line 49, in input_username_passwd
    userName = self.testdriver.find_element_by_id("userName")
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 289, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 791, in find_element
    'value': value})['value']
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: Unable to locate element: [id="userName"]

Traceback (most recent call last):
  File "login.py", line 49, in input_username_passwd
    userName = self.testdriver.find_element_by_id("userName")
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 289, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 791, in find_element
    'value': value})['value']
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: Unable to locate element: [id="userName"]

[ERROR] 2017-07-11 23:58:42,568-log.py:92 Traceback (most recent call last):
  File "login.py", line 63, in get_failed_page_message
    err_msg = self.testdriver.find_element_by_xpath('//*[@id="userForLogin"]/div[1]')
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 313, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 791, in find_element
    'value': value})['value']
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: Unable to locate element: //*[@id="userForLogin"]/div[1]

Traceback (most recent call last):
  File "login.py", line 63, in get_failed_page_message
    err_msg = self.testdriver.find_element_by_xpath('//*[@id="userForLogin"]/div[1]')
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 313, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 791, in find_element
    'value': value})['value']
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: Unable to locate element: //*[@id="userForLogin"]/div[1]

[ERROR] 2017-07-11 23:58:42,598-log.py:92 Traceback (most recent call last):
  File "login.py", line 49, in input_username_passwd
    userName = self.testdriver.find_element_by_id("userName")
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 289, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 791, in find_element
    'value': value})['value']
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: Unable to locate element: [id="userName"]

Traceback (most recent call last):
  File "login.py", line 49, in input_username_passwd
    userName = self.testdriver.find_element_by_id("userName")
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 289, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 791, in find_element
    'value': value})['value']
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: Unable to locate element: [id="userName"]

[ERROR] 2017-07-12 00:00:48,793-log.py:92 Traceback (most recent call last):
  File "login.py", line 65, in get_failed_page_message
    err_msg = self.testdriver.find_element_by_xpath('//*[@id="userForLogin"]/div[1]')
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 313, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 791, in find_element
    'value': value})['value']
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: Unable to locate element: //*[@id="userForLogin"]/div[1]

Traceback (most recent call last):
  File "login.py", line 65, in get_failed_page_message
    err_msg = self.testdriver.find_element_by_xpath('//*[@id="userForLogin"]/div[1]')
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 313, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 791, in find_element
    'value': value})['value']
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: Unable to locate element: //*[@id="userForLogin"]/div[1]

[ERROR] 2017-07-12 00:01:51,878-log.py:92 Traceback (most recent call last):
  File "login.py", line 65, in get_failed_page_message
    err_msg = self.testdriver.find_element_by_xpath('//*[@id="userForLogin"]/div[1]')
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 313, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 791, in find_element
    'value': value})['value']
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: Unable to locate element: //*[@id="userForLogin"]/div[1]

Traceback (most recent call last):
  File "login.py", line 65, in get_failed_page_message
    err_msg = self.testdriver.find_element_by_xpath('//*[@id="userForLogin"]/div[1]')
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 313, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 791, in find_element
    'value': value})['value']
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: Unable to locate element: //*[@id="userForLogin"]/div[1]

[ERROR] 2017-07-12 00:07:50,846-log.py:92 Traceback (most recent call last):
  File "login.py", line 68, in get_failed_page_message
    err_msg = self.testdriver.find_element_by_xpath('//*[@id="userForLogin"]/div[1]')
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 313, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 791, in find_element
    'value': value})['value']
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: Unable to locate element: //*[@id="userForLogin"]/div[1]

Traceback (most recent call last):
  File "login.py", line 68, in get_failed_page_message
    err_msg = self.testdriver.find_element_by_xpath('//*[@id="userForLogin"]/div[1]')
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 313, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 791, in find_element
    'value': value})['value']
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: Unable to locate element: //*[@id="userForLogin"]/div[1]

[ERROR] 2017-07-12 00:09:28,904-log.py:92 Traceback (most recent call last):
  File "login.py", line 68, in get_failed_page_message
    err_msg = self.testdriver.find_element_by_xpath('//*[@id="userForLogin"]/div[1]')
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 313, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 791, in find_element
    'value': value})['value']
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: Unable to locate element: //*[@id="userForLogin"]/div[1]

Traceback (most recent call last):
  File "login.py", line 68, in get_failed_page_message
    err_msg = self.testdriver.find_element_by_xpath('//*[@id="userForLogin"]/div[1]')
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 313, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 791, in find_element
    'value': value})['value']
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: Unable to locate element: //*[@id="userForLogin"]/div[1]

[ERROR] 2017-07-12 00:12:04,736-log.py:92 Traceback (most recent call last):
  File "login.py", line 68, in get_failed_page_message
    err_msg = self.testdriver.find_element_by_xpath('//*[@id="userForLogin"]/div[1]')
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 313, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 791, in find_element
    'value': value})['value']
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: Unable to locate element: //*[@id="userForLogin"]/div[1]

Traceback (most recent call last):
  File "login.py", line 68, in get_failed_page_message
    err_msg = self.testdriver.find_element_by_xpath('//*[@id="userForLogin"]/div[1]')
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 313, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 791, in find_element
    'value': value})['value']
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: Unable to locate element: //*[@id="userForLogin"]/div[1]

[ERROR] 2017-07-12 00:13:05,604-log.py:92 Traceback (most recent call last):
  File "login.py", line 68, in get_failed_page_message
    err_msg = self.testdriver.find_element_by_xpath('//*[@id="userForLogin"]/div[1]')
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 313, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 791, in find_element
    'value': value})['value']
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: Unable to locate element: //*[@id="userForLogin"]/div[1]

Traceback (most recent call last):
  File "login.py", line 68, in get_failed_page_message
    err_msg = self.testdriver.find_element_by_xpath('//*[@id="userForLogin"]/div[1]')
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 313, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 791, in find_element
    'value': value})['value']
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: Unable to locate element: //*[@id="userForLogin"]/div[1]

[ERROR] 2017-07-13 09:46:29,608-log.py:92 Traceback (most recent call last):
  File "C:\Users\annieren\PycharmProjects\autotest-master\src\login.py", line 57, in input_username_passwd
    submit_button = self.testdriver.find_element_by_xpath(""".//*[@id='compUserVo']/div/div/div[12]/div/div/button""")
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 313, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 791, in find_element
    'value': value})['value']
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: Unable to locate element: .//*[@id='compUserVo']/div/div/div[12]/div/div/button

Traceback (most recent call last):
  File "C:\Users\annieren\PycharmProjects\autotest-master\src\login.py", line 57, in input_username_passwd
    submit_button = self.testdriver.find_element_by_xpath(""".//*[@id='compUserVo']/div/div/div[12]/div/div/button""")
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 313, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 791, in find_element
    'value': value})['value']
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: Unable to locate element: .//*[@id='compUserVo']/div/div/div[12]/div/div/button

[ERROR] 2017-07-13 09:46:33,599-log.py:92 Traceback (most recent call last):
  File "C:\Users\annieren\PycharmProjects\autotest-master\src\login.py", line 57, in input_username_passwd
    submit_button = self.testdriver.find_element_by_xpath(""".//*[@id='compUserVo']/div/div/div[12]/div/div/button""")
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 313, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 791, in find_element
    'value': value})['value']
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: Unable to locate element: .//*[@id='compUserVo']/div/div/div[12]/div/div/button

Traceback (most recent call last):
  File "C:\Users\annieren\PycharmProjects\autotest-master\src\login.py", line 57, in input_username_passwd
    submit_button = self.testdriver.find_element_by_xpath(""".//*[@id='compUserVo']/div/div/div[12]/div/div/button""")
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 313, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 791, in find_element
    'value': value})['value']
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: Unable to locate element: .//*[@id='compUserVo']/div/div/div[12]/div/div/button

[ERROR] 2017-07-13 09:46:41,321-log.py:92 Traceback (most recent call last):
  File "C:\Users\annieren\PycharmProjects\autotest-master\src\login.py", line 57, in input_username_passwd
    submit_button = self.testdriver.find_element_by_xpath(""".//*[@id='compUserVo']/div/div/div[12]/div/div/button""")
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 313, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 791, in find_element
    'value': value})['value']
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: Unable to locate element: .//*[@id='compUserVo']/div/div/div[12]/div/div/button

Traceback (most recent call last):
  File "C:\Users\annieren\PycharmProjects\autotest-master\src\login.py", line 57, in input_username_passwd
    submit_button = self.testdriver.find_element_by_xpath(""".//*[@id='compUserVo']/div/div/div[12]/div/div/button""")
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 313, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 791, in find_element
    'value': value})['value']
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: Unable to locate element: .//*[@id='compUserVo']/div/div/div[12]/div/div/button

[ERROR] 2017-07-13 09:59:15,196-log.py:92 Traceback (most recent call last):
  File "C:\Users\annieren\PycharmProjects\autotest-master\src\login.py", line 57, in input_username_passwd
    submit_button = self.testdriver.find_element_by_xpath(""".//*[@id='compUserVo']/div/div/div[12]/div/div/button""")
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 313, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 791, in find_element
    'value': value})['value']
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: Unable to locate element: .//*[@id='compUserVo']/div/div/div[12]/div/div/button

Traceback (most recent call last):
  File "C:\Users\annieren\PycharmProjects\autotest-master\src\login.py", line 57, in input_username_passwd
    submit_button = self.testdriver.find_element_by_xpath(""".//*[@id='compUserVo']/div/div/div[12]/div/div/button""")
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 313, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 791, in find_element
    'value': value})['value']
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: Unable to locate element: .//*[@id='compUserVo']/div/div/div[12]/div/div/button

[ERROR] 2017-07-13 10:00:54,131-log.py:92 Traceback (most recent call last):
  File "C:\Users\annieren\PycharmProjects\autotest-master\src\login.py", line 57, in input_username_passwd
    submit_button = self.testdriver.find_element_by_xpath(""".//*[@id='compUserVo']/div/div/div[12]/div/div/button""")
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 313, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 791, in find_element
    'value': value})['value']
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: Unable to locate element: .//*[@id='compUserVo']/div/div/div[12]/div/div/button

Traceback (most recent call last):
  File "C:\Users\annieren\PycharmProjects\autotest-master\src\login.py", line 57, in input_username_passwd
    submit_button = self.testdriver.find_element_by_xpath(""".//*[@id='compUserVo']/div/div/div[12]/div/div/button""")
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 313, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 791, in find_element
    'value': value})['value']
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: Unable to locate element: .//*[@id='compUserVo']/div/div/div[12]/div/div/button

[ERROR] 2017-07-13 10:00:57,894-log.py:92 Traceback (most recent call last):
  File "C:\Users\annieren\PycharmProjects\autotest-master\src\login.py", line 57, in input_username_passwd
    submit_button = self.testdriver.find_element_by_xpath(""".//*[@id='compUserVo']/div/div/div[12]/div/div/button""")
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 313, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 791, in find_element
    'value': value})['value']
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: Unable to locate element: .//*[@id='compUserVo']/div/div/div[12]/div/div/button

Traceback (most recent call last):
  File "C:\Users\annieren\PycharmProjects\autotest-master\src\login.py", line 57, in input_username_passwd
    submit_button = self.testdriver.find_element_by_xpath(""".//*[@id='compUserVo']/div/div/div[12]/div/div/button""")
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 313, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 791, in find_element
    'value': value})['value']
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: Unable to locate element: .//*[@id='compUserVo']/div/div/div[12]/div/div/button

[ERROR] 2017-07-13 10:01:03,529-log.py:92 Traceback (most recent call last):
  File "C:\Users\annieren\PycharmProjects\autotest-master\src\login.py", line 57, in input_username_passwd
    submit_button = self.testdriver.find_element_by_xpath(""".//*[@id='compUserVo']/div/div/div[12]/div/div/button""")
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 313, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 791, in find_element
    'value': value})['value']
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: Unable to locate element: .//*[@id='compUserVo']/div/div/div[12]/div/div/button

Traceback (most recent call last):
  File "C:\Users\annieren\PycharmProjects\autotest-master\src\login.py", line 57, in input_username_passwd
    submit_button = self.testdriver.find_element_by_xpath(""".//*[@id='compUserVo']/div/div/div[12]/div/div/button""")
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 313, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 791, in find_element
    'value': value})['value']
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: Unable to locate element: .//*[@id='compUserVo']/div/div/div[12]/div/div/button

[ERROR] 2017-07-13 11:27:20,766-log.py:92 Traceback (most recent call last):
  File "register.py", line 91, in get_failed_page_message
    err_cnname_msg = self.testdriver.find_element_by_id('comp.cnName.errors')
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 289, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 791, in find_element
    'value': value})['value']
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: Unable to locate element: [id="comp.cnName.errors"]

Traceback (most recent call last):
  File "register.py", line 91, in get_failed_page_message
    err_cnname_msg = self.testdriver.find_element_by_id('comp.cnName.errors')
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 289, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 791, in find_element
    'value': value})['value']
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: Unable to locate element: [id="comp.cnName.errors"]

[ERROR] 2017-07-13 11:52:16,740-log.py:92 Traceback (most recent call last):
  File "register.py", line 124, in is_register_status
    cc = self.testdriver.find_element_by_xpath("""html/body/div[1]/div/div/div/div[1]/h3""")
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 313, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 791, in find_element
    'value': value})['value']
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: Unable to locate element: html/body/div[1]/div/div/div/div[1]/h3

Traceback (most recent call last):
  File "register.py", line 124, in is_register_status
    cc = self.testdriver.find_element_by_xpath("""html/body/div[1]/div/div/div/div[1]/h3""")
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 313, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 791, in find_element
    'value': value})['value']
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: Unable to locate element: html/body/div[1]/div/div/div/div[1]/h3

[ERROR] 2017-07-13 11:52:16,756-log.py:92 Traceback (most recent call last):
  File "register.py", line 92, in get_failed_page_message
    err_cnname_msg = self.testdriver.find_element_by_id('comp.cnName.errors')
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 289, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 791, in find_element
    'value': value})['value']
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: Unable to locate element: [id="comp.cnName.errors"]

Traceback (most recent call last):
  File "register.py", line 92, in get_failed_page_message
    err_cnname_msg = self.testdriver.find_element_by_id('comp.cnName.errors')
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 289, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 791, in find_element
    'value': value})['value']
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: Unable to locate element: [id="comp.cnName.errors"]

[ERROR] 2017-07-13 11:53:48,226-log.py:92 Traceback (most recent call last):
  File "register.py", line 122, in is_register_status
    cc = self.testdriver.find_element_by_xpath("""html/body/div[1]/div/div/div/div[1]/h3""")
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 313, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 791, in find_element
    'value': value})['value']
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: Unable to locate element: html/body/div[1]/div/div/div/div[1]/h3

Traceback (most recent call last):
  File "register.py", line 122, in is_register_status
    cc = self.testdriver.find_element_by_xpath("""html/body/div[1]/div/div/div/div[1]/h3""")
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 313, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 791, in find_element
    'value': value})['value']
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: Unable to locate element: html/body/div[1]/div/div/div/div[1]/h3

[ERROR] 2017-07-13 13:32:14,938-log.py:92 Traceback (most recent call last):
  File "register.py", line 122, in is_register_status
    cc = self.testdriver.find_element_by_xpath("""html/body/div[1]/div/div/div/div[1]/h3""")
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 313, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 791, in find_element
    'value': value})['value']
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: Unable to locate element: html/body/div[1]/div/div/div/div[1]/h3

Traceback (most recent call last):
  File "register.py", line 122, in is_register_status
    cc = self.testdriver.find_element_by_xpath("""html/body/div[1]/div/div/div/div[1]/h3""")
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 313, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 791, in find_element
    'value': value})['value']
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: Unable to locate element: html/body/div[1]/div/div/div/div[1]/h3

[ERROR] 2017-07-13 13:42:47,823-log.py:92 Traceback (most recent call last):
  File "register.py", line 122, in is_register_status
    cc = self.testdriver.find_element_by_xpath("""html/body/div[1]/div/div/div/div[1]/h3""")
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 313, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 791, in find_element
    'value': value})['value']
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: Unable to locate element: html/body/div[1]/div/div/div/div[1]/h3

Traceback (most recent call last):
  File "register.py", line 122, in is_register_status
    cc = self.testdriver.find_element_by_xpath("""html/body/div[1]/div/div/div/div[1]/h3""")
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 313, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 791, in find_element
    'value': value})['value']
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: Unable to locate element: html/body/div[1]/div/div/div/div[1]/h3

[ERROR] 2017-07-13 14:17:44,529-log.py:92 Traceback (most recent call last):
  File "register.py", line 157, in is_register_status
    cc = self.testdriver.find_element_by_xpath("""html/body/div[1]/div/div/div/div[1]/h3""")
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 313, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 791, in find_element
    'value': value})['value']
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: Unable to locate element: html/body/div[1]/div/div/div/div[1]/h3

Traceback (most recent call last):
  File "register.py", line 157, in is_register_status
    cc = self.testdriver.find_element_by_xpath("""html/body/div[1]/div/div/div/div[1]/h3""")
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 313, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 791, in find_element
    'value': value})['value']
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: Unable to locate element: html/body/div[1]/div/div/div/div[1]/h3

[ERROR] 2017-07-13 14:18:46,661-log.py:92 Traceback (most recent call last):
  File "register.py", line 157, in is_register_status
    cc = self.testdriver.find_element_by_xpath("""html/body/div[1]/div/div/div/div[1]/h3""")
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 313, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 791, in find_element
    'value': value})['value']
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: Unable to locate element: html/body/div[1]/div/div/div/div[1]/h3

Traceback (most recent call last):
  File "register.py", line 157, in is_register_status
    cc = self.testdriver.find_element_by_xpath("""html/body/div[1]/div/div/div/div[1]/h3""")
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 313, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 791, in find_element
    'value': value})['value']
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: Unable to locate element: html/body/div[1]/div/div/div/div[1]/h3

